spring-web-sample-web/src/main/java/at/activesolution/samples/web/view/controller/MitarbeiterBean.java
package at.activesolution.samples.web.view.controller;

import at.activesolution.samples.web.core.model.domain.Mitarbeiter;
import at.activesolution.samples.web.core.service.api.IMitarbeiterService;
import org.springframework.context.annotation.Scope;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.List;

/**
 * Bean zur Anzeige der Mitarbeiterliste und zum Bearbeiten von Mitarbeitern.
 */
@Named
@Scope("view")
public class MitarbeiterBean extends BaseBackingBean {

    @Inject
    private IMitarbeiterService mitarbeiterService;

    // aktuell bearbeiteter Mitarbeiter
    private Mitarbeiter currentMitarbeiter;

    // Liste aller Mitarbeiter
    private List<Mitarbeiter> mitarbeiterList;

    public List<Mitarbeiter> getMitarbeiterList() {
        if (mitarbeiterList == null) {
            mitarbeiterList = mitarbeiterService.listMitarbeiter();
        }
        return mitarbeiterList;
    }

    /**
     * Setzt einen Mitarbeiter zur Bearbeitung.
     *
     * @param mitarbeiter der zu bearbeitende Mitarbeiter
     */
    public void actionEdit(Mitarbeiter mitarbeiter) {
        this.currentMitarbeiter = mitarbeiter;
    }

    /**
     * Erstellt ein neues Mitarbeiter Objekt zur Anlage.
     */
    public void actionNew() {
        currentMitarbeiter = new Mitarbeiter();
    }

    /**
     * Loescht den uebergebenen Mitarbeiter aus der DB
     *
     * @param mitarbeiter zu loeschender Mitarbeiter
     */
    public void actionDelete(Mitarbeiter mitarbeiter) {
        try {
            mitarbeiterService.deleteMitarbeiter(mitarbeiter);

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Mitarbeiter wurde gelöscht!"));

            reset();
        } catch (Exception e) {
            handleException(e);
        }
    }

    /**
     * Speichert den aktuell bearbeiteten Mitarbeiter.
     */
    public void actionSave() {
        try {
            mitarbeiterService.saveMitarbeiter(currentMitarbeiter);

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Daten wurden gespeichert!"));

            reset();
        } catch (Exception e) {
            handleException(e);
        }
    }

    public void actionCancel() {
        reset();
    }

    /**
     * Mitarbeiterliste und aktuellen Mitarbeiter zuruecksetzen
     */
    private void reset() {
        currentMitarbeiter = null;
        mitarbeiterList = null;
    }

    public Mitarbeiter getCurrentMitarbeiter() {
        return currentMitarbeiter;
    }

    public void setCurrentMitarbeiter(Mitarbeiter currentMitarbeiter) {
        this.currentMitarbeiter = currentMitarbeiter;
    }

}

spring-web-sample-web/src/main/java/at/activesolution/samples/web/view/controller/MitarbeiterSearchBean.java
package at.activesolution.samples.web.view.controller;

import java.util.List;

import javax.inject.Inject;
import javax.inject.Named;

import org.springframework.context.annotation.Scope;

import at.activesolution.samples.web.core.model.criteria.MitarbeiterCriteria;
import at.activesolution.samples.web.core.model.domain.Mitarbeiter;
import at.activesolution.samples.web.core.service.api.IMitarbeiterService;

/**
 * Bean zur Suche nach Mitarbeitern.
 */
@Named
@Scope("view")
public class MitarbeiterSearchBean extends BaseBackingBean {

    @Inject
    private IMitarbeiterService mitarbeiterService;

    private MitarbeiterCriteria mitarbeiterCriteria = new MitarbeiterCriteria();

    // Liste aller Mitarbeiter
    private List<Mitarbeiter> mitarbeiterList;

    public List<Mitarbeiter> getMitarbeiterList() {
        return mitarbeiterList;
    }

    public MitarbeiterCriteria getMitarbeiterCriteria() {
        return mitarbeiterCriteria;
    }

    public void actionSearch() {
        mitarbeiterList = mitarbeiterService.searchMitarbeiter(mitarbeiterCriteria);
    }

    public void actionCancel() {
        mitarbeiterList = null;
        mitarbeiterCriteria = new MitarbeiterCriteria();
    }
}

spring-web-sample-web/src/main/java/at/activesolution/samples/web/view/controller/UserBean.java
package at.activesolution.samples.web.view.controller;

import javax.inject.Named;

import org.springframework.context.annotation.Scope;

/**
 * Benutzer Konfiguration.
 */
@Named
@Scope("session")
public class UserBean {

    // der Default-Date-Pattern fuer den User
    private static final String DATE_PATTERN = "dd.MM.yyyy";
    // die Default-Theme
    private String theme = "omega";

    /**
     * Liefert den Date-Pattern fuer die Verwendung im JSF Calendar.<br>
     * Koennte z.B. aus der FacesConfig je nach Locale ermittelt werden.
     *
     * @return DateFormat als String
     */
    public String getDatePattern() {
        return DATE_PATTERN;
    }

    public String getTheme() {
        return theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }


}

spring-web-sample-web/src/main/webapp/mitarbeiter/_mitarbeiter_edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition>
        <!-- Dialog zum Bearbeiten von Mitarbeitern -->
        <p:dialog id="mitarbeiterEditDialog" widgetVar="mitarbeiterEditDialog" header="Mitarbeiter bearbeiten"
                  position="center" modal="true" closable="false" closeOnEscape="false" dynamic="true"
                  maximizable="false" minimizable="false" resizable="false">
            <h:form id="mitarbeiterEditForm">
                <h:panelGrid columns="2" styleClass="fullwidth-input">
                    <p:outputLabel for="nachname" value="Nachname"/>
                    <p:inputText id="nachname" label="Nachname"
                                 value="#{mitarbeiterBean.currentMitarbeiter.nachname}"/>

                    <p:outputLabel for="vorname" value="Vorname"/>
                    <p:inputText id="vorname" label="Vorname"
                                 value="#{mitarbeiterBean.currentMitarbeiter.vorname}"/>

                    <p:outputLabel for="geburtsdatum" value="Geburtsdatum"/>
                    <p:calendar id="geburtsdatum" label="Geburtsdatum"
                                value="#{mitarbeiterBean.currentMitarbeiter.geburtsdatum}"
                                pattern="#{userBean.datePattern}" navigator="true"/>

                    <p:outputLabel for="geschlecht" value="Geschlecht"/>
                    <p:selectOneMenu id="geschlecht" label="Geschlecht"
                                     value="#{mitarbeiterBean.currentMitarbeiter.geschlecht}">
                        <f:selectItem itemValue="M" itemLabel="M"/>
                        <f:selectItem itemValue="W" itemLabel="W"/>
                    </p:selectOneMenu>

                    <p:outputLabel for="abteilung" value="Abteilung"/>
                    <p:selectOneMenu id="abteilung" label="Abteilung"
                                     value="#{mitarbeiterBean.currentMitarbeiter.abteilung}"
                                     converter="#{abteilungConverter}">
                        <f:selectItem value="#{null}" noSelectionOption="true"/>
                        <f:selectItems value="#{lookupValuesBean.abteilungen}"/>
                    </p:selectOneMenu>

                    <p:outputLabel for="eintrittsdatum" value="Eintrittsdatum"/>
                    <p:calendar id="eintrittsdatum" label="Eintrittsdatum"
                                value="#{mitarbeiterBean.currentMitarbeiter.eintrittsdatum}"
                                pattern="#{userBean.datePattern}" navigator="true"/>

                    <p:outputLabel for="detail" value="Details"/>
                    <p:inputTextarea id="detail" label="Details"
                                 value="#{mitarbeiterBean.currentMitarbeiter.detail}" style="max-height: 150px"/>
                </h:panelGrid>
                <p:commandButton value="Speichern" action="#{mitarbeiterBean.actionSave}" process="@form"
                                 update=":contentForm @form"
                                 oncomplete="if(operationSuccessful(args)) { PF('mitarbeiterEditDialog').hide() }"
                                 icon="fa fa-fw fa-check">
                    <p:resetInput target="mitarbeiterEditForm"/>
                </p:commandButton>
                <p:commandButton value="Abbrechen" action="#{mitarbeiterBean.actionCancel}" process="@this"
                                 oncomplete="PF('mitarbeiterEditDialog').hide()"
                                 icon="fa fa-fw fa-close">
                    <p:resetInput target="mitarbeiterEditForm"/>
                </p:commandButton>

            </h:form>
        </p:dialog>

    </ui:composition>


</html>

spring-web-sample-web/src/main/webapp/mitarbeiter/mitarbeiter.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition
            template="/resources/templates/layout/simpleTemplate.xhtml">
        <ui:define name="title">Mitarbeiter</ui:define>
        <ui:define name="content">
            <p:dataTable value="#{mitarbeiterBean.mitarbeiterList}" var="row" id="dataTable" rows="20" paginator="true"
                         paginatorPosition="bottom">
                <p:column styleClass="smallCol">
                    <p:rowToggler/>
                </p:column>
                <p:column id="actionColumn" styleClass="smallCol">
                    <p:commandLink id="mitarbeiterEditCmd"
                                   action="#{mitarbeiterBean.actionEdit(row)}"
                                   oncomplete="PF('mitarbeiterEditDialog').show()" update=":mitarbeiterEditForm"
                                   title="Mitarbeiter bearbeiten">
                        <span class="fa fa-fw fa-edit"></span>
                    </p:commandLink>
                    <p:commandLink id="mitarbeiterDeleteCmd"
                                   action="#{mitarbeiterBean.actionDelete(row)}"
                                   update="@form"
                                   title="Mitarbeiter löschen">
                        <span class="fa fa-fw fa-trash"></span>
                    </p:commandLink>
                </p:column>
                <p:column id="nachnameColumn" headerText="Nachname" sortBy="#{row.nachname}">
                    <h:outputText value="#{row.nachname}"/>
                </p:column>
                <p:column id="vornameColumn" headerText="Vorname" sortBy="#{row.vorname}">
                    <h:outputText value="#{row.vorname}"/>
                </p:column>
                <p:column id="geburtsdatumColumn" headerText="Geburtsdatum" sortBy="#{row.geburtsdatum}"
                          styleClass="right">
                    <h:outputText value="#{row.geburtsdatum}">
                        <f:convertDateTime type="date"/>
                    </h:outputText>
                </p:column>
                <p:column id="geschlechtColumn" headerText="Geschlecht" sortBy="#{row.geschlecht}" styleClass="center">
                    <h:outputText value="#{row.geschlecht}"/>
                </p:column>
                <p:column id="abteilungColumn" headerText="Abteilung" sortBy="#{row.abteilung.kuerzel}"
                          styleClass="center">
                    <h:outputText value="#{row.abteilung.kuerzel}" title="#{row.abteilung.bezeichnung}"/>
                </p:column>
                <p:column id="eintrittsdatumColumn" headerText="Eintrittsdatum" sortBy="#{row.eintrittsdatum}"
                          styleClass="right">
                    <h:outputText value="#{row.eintrittsdatum}">
                        <f:convertDateTime type="date"/>
                    </h:outputText>
                </p:column>

                <p:rowExpansion>
                    <h3>Weitere Informationen</h3>
                    <h:outputText value="#{row.detail}" />
                </p:rowExpansion>

            </p:dataTable>
            <br/>
            <p:commandButton value="Neuer Mitarbeiter" action="#{mitarbeiterBean.actionNew}" icon="fa fa-fw fa-plus"
                             oncomplete="PF('mitarbeiterEditDialog').show()" update=":mitarbeiterEditForm"/>
        </ui:define>

        <ui:define name="nonFormContent">
            <ui:include src="_mitarbeiter_edit.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

spring-web-sample-web/src/main/webapp/mitarbeiter/mitarbeiter_search.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition
        template="/resources/templates/layout/simpleTemplate.xhtml">
    <ui:define name="title">Mitarbeiter</ui:define>
    <ui:define name="content">
        <p:panel header="Suche">
            <h:panelGrid columns="8" style="width: 100%" styleClass="fullwidth-input mitarbeiter-search">
                <p:outputLabel for="nachname" value="Nachname"/>
                <p:inputText id="nachname" label="Nachname"
                             value="#{mitarbeiterSearchBean.mitarbeiterCriteria.nachname}"/>

                <p:outputLabel for="vorname" value="Vorname"/>
                <p:inputText id="vorname" label="Vorname"
                             value="#{mitarbeiterSearchBean.mitarbeiterCriteria.vorname}"/>

                <p:outputLabel for="geschlecht" value="Geschlecht"/>
                <p:selectOneMenu id="geschlecht" label="Geschlecht"
                                 value="#{mitarbeiterSearchBean.mitarbeiterCriteria.geschlecht}">
                    <f:selectItem itemValue="#{null}" noSelectionOption="true"/>
                    <f:selectItem itemValue="M" itemLabel="M"/>
                    <f:selectItem itemValue="W" itemLabel="W"/>
                </p:selectOneMenu>

                <p:outputLabel for="abteilung" value="Abteilung"/>
                <p:inputText id="abteilung" label="Abteilung"
                             value="#{mitarbeiterSearchBean.mitarbeiterCriteria.abteilung}"/>
            </h:panelGrid>

            <p:commandButton id="cmdSearch" value="Suche" action="#{mitarbeiterSearchBean.actionSearch}" process="@form" update="@form"
                             icon="fa fa-fw fa-search"/>
            <p:commandButton id="cmdCancel" value="Zurücksetzen" action="#{mitarbeiterSearchBean.actionCancel}" process="@this" update="@form"
                             icon="fa fa-fw fa-close"/>
        </p:panel>

        <p:dataTable value="#{mitarbeiterSearchBean.mitarbeiterList}" var="row" id="dataTable" rows="20" paginator="true"
                     paginatorPosition="bottom" rendered="#{mitarbeiterSearchBean.mitarbeiterList != null}" style="margin-top: 1em">
            <p:column styleClass="smallCol">
                <p:rowToggler/>
            </p:column>
            <p:column id="nachnameColumn" headerText="Nachname" sortBy="#{row.nachname}">
                <h:outputText value="#{row.nachname}"/>
            </p:column>
            <p:column id="vornameColumn" headerText="Vorname" sortBy="#{row.vorname}">
                <h:outputText value="#{row.vorname}"/>
            </p:column>
            <p:column id="geburtsdatumColumn" headerText="Geburtsdatum" sortBy="#{row.geburtsdatum}"
                      styleClass="right">
                <h:outputText value="#{row.geburtsdatum}">
                    <f:convertDateTime type="date"/>
                </h:outputText>
            </p:column>
            <p:column id="geschlechtColumn" headerText="Geschlecht" sortBy="#{row.geschlecht}" styleClass="center">
                <h:outputText value="#{row.geschlecht}"/>
            </p:column>
            <p:column id="abteilungColumn" headerText="Abteilung" sortBy="#{row.abteilung.kuerzel}"
                      styleClass="center">
                <h:outputText value="#{row.abteilung.kuerzel}" title="#{row.abteilung.bezeichnung}"/>
            </p:column>
            <p:column id="eintrittsdatumColumn" headerText="Eintrittsdatum" sortBy="#{row.eintrittsdatum}"
                      styleClass="right">
                <h:outputText value="#{row.eintrittsdatum}">
                    <f:convertDateTime type="date"/>
                </h:outputText>
            </p:column>

            <p:rowExpansion>
                <h3>Weitere Informationen</h3>
                <h:outputText value="#{row.detail}"/>
            </p:rowExpansion>

        </p:dataTable>

    </ui:define>

</ui:composition>

</html>